name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch - Check
  pull_request:
    branches:
      - master
    paths:
      - 'src/components/**.*'
  push:
    branches:
      - master
    tag:
      - v2.*

jobs:
  install-lint-test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Setup-Node
      uses: actions/setup-node@v1

    # # - uses: c-hive/gha-yarn-cache@v1

    - name: Install JS dependencies
      run: npm install

    - name: EsLint Checks
      run: npm run lint
    
    - name: Testcase Checks
      run: npm run test

  build-android:
    needs: install-lint-test
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
    
    
