name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch - Check
  pull_request:
    branches:
      - master
    paths:
      - 'src/components/**.*'
  push:
    branches:
      - master
    tag:
      - v2.*

jobs:
  lint:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Setup-Node
      uses: actions/setup-node@v1

    # # - uses: c-hive/gha-yarn-cache@v1

    - name: Install JS dependencies
      run: npm install

    - name: EsLint Checks
      run: npm run lint
    
    - name: Testcase Checks
      run: npm run test
    
