name: CI

on:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Setup-Node
      uses: actions/setup-node@v1

    # - uses: c-hive/gha-yarn-cache@v1

    # - name: Install JS dependencies
    #   run: npm install

    - name: Test
      run: npm run lint
