name: CI

on:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1

    - uses: c-hive/gha-yarn-cache@v1

    - name: Install JS dependencies
      run: npm install
    - name: Test
      run: npm run lint
